### ISSUE TITLE
Need help with external module "redcap-em-export-repeating-data"

### ISSUE THREAD

**Issue by BPG-2010** [susom/redcap-em-export-repeating-data#2]
Hi, 
I am trying to link a repeating form within another repeating form (scenario 2 described in the text). I link form 3 with form 2 with the action tag FORMINSTANCE and INSTANCETABLE_REF on the form 3 (on the variable which identifies the form 2), but the result does not provide the desired output. Is there any contact through whom I can get help in using external module "redcap-em-export-repeating-data"? It would be great if I can get some! Thank you very much!

**Comment by eyl407** [comment]
I can take at look if you want to send your data dictionary for these two forms.

Eileen

On Aug 2, 2022, at 3:09 AM, BPG-2010 ***@***.******@***.***>> wrote:

[EXT]


Hi,
I am trying to link a repeating form within another repeating form (scenario 2 described in the text). I link form 3 with form 2 with the action tag FORMINSTANCE and INSTANCETABLE_REF on the form 3 (on the variable which identifies the form 2), but the result does not provide the desired output. Is there any contact through whom I can get help in using external module "redcap-em-export-repeating-data"? It would be great if I can get some! Thank you very much!

**Comment by BPG-2010** [comment]
> 

Thank you very much for the offer, Eileen! Recently I got to fix it myself, as it was due to some sort of error in the mentioning of FORMINSTANCE!

**Comment by susanweber** [comment]
Sounds like this has been resolved
