### ISSUE TITLE
Only one repeating form

### ISSUE THREAD

**Issue by melTr** [susom/redcap-em-export-repeating-data#3]
I have only one repeating form. According to documentation, it should need any other configurations. 
But I got this message "Please ask your REDCap administrator to configure this project with @PRINCIPAL_DATE and/or @FORMINSTANCE action tags as per the documentation for this module".
Do I really need something else to get it working?
Redcap version is 12.4.12
Thanks.

**Comment by eyl407** [comment]
You need some variable on the repeating form to act as a unique identifier for the form.  That variable should be marked as PRINCIPAL_DATE if it's a date, or FORMINSTANCE for a different type of identifier.

________________________________
From: melTr ***@***.***>
Sent: Wednesday, August 17, 2022 10:45 AM
To: susom/redcap-em-export-repeating-data ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [susom/redcap-em-export-repeating-data] Only one repeating form (Issue #3)

[EXT]

I have only one repeating form. According to documentation, it should need any other configurations.
But I got this message "Please ask your REDCap administrator to configure this project with @PRINCIPAL_DATE and/or @FORMINSTANCE action tags as per the documentation for this module".
Do I really need something else to get it working?
Redcap version is 12.4.12
Thanks.
